set -euo pipefail

PRODUCT="${1:-}"
VERSION="${2:-}"

if [[ -z "$PRODUCT" || -z "$VERSION" ]]; then
  echo "Usage: $0 <product> <version>"
  echo "  e.g. $0 gix v0.2.7"
  exit 1
fi

VERSION_NUM="${VERSION#v}"

META_FILE="META.d/${PRODUCT}.hcl"
if [[ ! -f "$META_FILE" ]]; then
  echo "Error: $META_FILE not found"
  echo "Create it first following the format in META.d/gix.hcl"
  exit 1
fi

parse_field() {
  grep -m1 "$1" "$META_FILE" | sed 's/.*= *"//' | sed 's/".*//'
}

parse_bool() {
  grep -m1 "$1" "$META_FILE" | grep -q "true" && echo "true" || echo "false"
}

NAME=$(parse_field "name")
DESC=$(parse_field "description")
HOMEPAGE=$(parse_field "homepage")
LICENSE=$(parse_field "license")
GITHUB_OWNER=$(parse_field "owner")
GITHUB_REPO=$(parse_field "repo")
BINARY_TEMPLATE=$(parse_field "binary_template")

DARWIN_AMD64=$(parse_bool "darwin_amd64")
DARWIN_ARM64=$(parse_bool "darwin_arm64")
LINUX_AMD64=$(parse_bool "linux_amd64")
LINUX_ARM64=$(parse_bool "linux_arm64")

BASE_URL="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/${VERSION}"

echo "Generating formula for ${NAME} ${VERSION}..."
echo "  Source: ${BASE_URL}"

CHECKSUMS_URL="${BASE_URL}/checksums.txt"
echo "  Fetching checksums from ${CHECKSUMS_URL}..."

CHECKSUMS=$(curl -fsSL "$CHECKSUMS_URL" 2>/dev/null || true)

if [[ -z "$CHECKSUMS" ]]; then
  echo "Warning: Could not fetch checksums.txt — SHA256 values will be empty"
  echo "         Fill them in manually or re-run after the release is published"
  CHECKSUMS=""
fi

get_sha() {
  local binary="$1"
  echo "$CHECKSUMS" | grep "$binary" | awk '{print $1}' || echo "TODO_SHA256"
}

binary_name() {
  local os="$1" arch="$2"
  echo "${BINARY_TEMPLATE}" | sed "s/{os}/$os/" | sed "s/{arch}/$arch/"
}

DARWIN_ARM64_BIN=$(binary_name "darwin" "arm64")
DARWIN_AMD64_BIN=$(binary_name "darwin" "amd64")
LINUX_ARM64_BIN=$(binary_name "linux" "arm64")
LINUX_AMD64_BIN=$(binary_name "linux" "amd64")

DARWIN_ARM64_SHA=$(get_sha "$DARWIN_ARM64_BIN")
DARWIN_AMD64_SHA=$(get_sha "$DARWIN_AMD64_BIN")
LINUX_ARM64_SHA=$(get_sha "$LINUX_ARM64_BIN")
LINUX_AMD64_SHA=$(get_sha "$LINUX_AMD64_BIN")


FORMULA_FILE="Formula/${NAME}.rb"

CLASS_NAME="$(echo "${NAME:0:1}" | tr '[:lower:]' '[:upper:]')${NAME:1}"

cat > "$FORMULA_FILE" << FORMULA
# Formula/${NAME}.rb
# Generated by util/formula_templater.sh — do not edit by hand.
# To update: ./util/formula_templater.sh ${NAME} <version>
class ${CLASS_NAME} < Formula
  desc "${DESC}"
  homepage "${HOMEPAGE}"
  version "${VERSION_NUM}"
  license "${LICENSE}"

FORMULA

if [[ "$DARWIN_ARM64" == "true" || "$DARWIN_AMD64" == "true" ]]; then
  cat >> "$FORMULA_FILE" << FORMULA
  on_macos do
FORMULA

  if [[ "$DARWIN_ARM64" == "true" ]]; then
    cat >> "$FORMULA_FILE" << FORMULA
    if Hardware::CPU.arm?
      url "${BASE_URL}/${DARWIN_ARM64_BIN}"
      sha256 "${DARWIN_ARM64_SHA}"

      def install
        bin.install "${DARWIN_ARM64_BIN}" => "${NAME}"
      end
    end
FORMULA
  fi

  if [[ "$DARWIN_AMD64" == "true" ]]; then
    if [[ "$DARWIN_ARM64" == "true" ]]; then
      cat >> "$FORMULA_FILE" << FORMULA

    if Hardware::CPU.intel?
      url "${BASE_URL}/${DARWIN_AMD64_BIN}"
      sha256 "${DARWIN_AMD64_SHA}"

      def install
        bin.install "${DARWIN_AMD64_BIN}" => "${NAME}"
      end
    end
FORMULA
    else
      cat >> "$FORMULA_FILE" << FORMULA
    url "${BASE_URL}/${DARWIN_AMD64_BIN}"
    sha256 "${DARWIN_AMD64_SHA}"

    def install
      bin.install "${DARWIN_AMD64_BIN}" => "${NAME}"
    end
FORMULA
    fi
  fi

  cat >> "$FORMULA_FILE" << FORMULA
  end

FORMULA
fi

# linux block
if [[ "$LINUX_ARM64" == "true" || "$LINUX_AMD64" == "true" ]]; then
  cat >> "$FORMULA_FILE" << FORMULA
  on_linux do
FORMULA

  if [[ "$LINUX_ARM64" == "true" ]]; then
    cat >> "$FORMULA_FILE" << FORMULA
    if Hardware::CPU.arm?
      url "${BASE_URL}/${LINUX_ARM64_BIN}"
      sha256 "${LINUX_ARM64_SHA}"

      def install
        bin.install "${LINUX_ARM64_BIN}" => "${NAME}"
      end
    end
FORMULA
  fi

  if [[ "$LINUX_AMD64" == "true" ]]; then
    if [[ "$LINUX_ARM64" == "true" ]]; then
      cat >> "$FORMULA_FILE" << FORMULA

    if Hardware::CPU.intel?
      url "${BASE_URL}/${LINUX_AMD64_BIN}"
      sha256 "${LINUX_AMD64_SHA}"

      def install
        bin.install "${LINUX_AMD64_BIN}" => "${NAME}"
      end
    end
FORMULA
    else
      cat >> "$FORMULA_FILE" << FORMULA
    url "${BASE_URL}/${LINUX_AMD64_BIN}"
    sha256 "${LINUX_AMD64_SHA}"

    def install
      bin.install "${LINUX_AMD64_BIN}" => "${NAME}"
    end
FORMULA
    fi
  fi

  cat >> "$FORMULA_FILE" << FORMULA
  end

FORMULA
fi

cat >> "$FORMULA_FILE" << FORMULA
  test do
    system "#{bin}/${NAME}", "--version"
  end
end
FORMULA

echo "  Generated ${FORMULA_FILE}"
echo ""
echo "Done. Review the formula and commit:"
echo "  git add ${FORMULA_FILE}"
echo "  git commit -m \"chore: update ${NAME} formula to ${VERSION}\""