# Formula/gix.rb
# Generated by util/formula_templater.sh — do not edit by hand.
# To update: ./util/formula_templater.sh gix <version>
class Gix < Formula
  desc "Git-enhancing CLI powered by AI"
  homepage "https://github.com/ademajagon/gix"
  version "0.2.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ademajagon/gix/releases/download/v0.2.10/gix-darwin-arm64"
      sha256 "1797fe3bc5405b682a6c9eabdbb4d74c70c05e8adb2eeee01d49d31ce6d9b3d4"

      def install
        bin.install "gix-darwin-arm64" => "gix"
      end
    end

    if Hardware::CPU.intel?
      url "https://github.com/ademajagon/gix/releases/download/v0.2.10/gix-darwin-amd64"
      sha256 "3abf3534ddea2f15fa728bb6526999dbeb2360b52ea172f239094e7fae70d22e"

      def install
        bin.install "gix-darwin-amd64" => "gix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/ademajagon/gix/releases/download/v0.2.10/gix-linux-arm64"
      sha256 "a8f2121d4b7a0b2b4a04de64a82decfaa61d71d04e10e626ccaf9c8eaa48e32a"

      def install
        bin.install "gix-linux-arm64" => "gix"
      end
    end

    if Hardware::CPU.intel?
      url "https://github.com/ademajagon/gix/releases/download/v0.2.10/gix-linux-amd64"
      sha256 "b6f29ac936a024b5d6d10c1bc7b4b41a3e3f3c67caaf737b988bef4d4bff81fe"

      def install
        bin.install "gix-linux-amd64" => "gix"
      end
    end
  end

  test do
    system "#{bin}/gix", "--version"
  end
end
