# Formula/gix.rb
# Generated by util/formula_templater.sh — do not edit by hand.
# To update: ./util/formula_templater.sh gix <version>
class Gix < Formula
  desc "Git-enhancing CLI powered by AI"
  homepage "https://github.com/ademajagon/gix"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ademajagon/gix/releases/download/v0.3.1/gix-darwin-arm64"
      sha256 "753ac2222ca73062320756fdb8144f0eeb168bfd7257469923bff55586b57df4"

      def install
        bin.install "gix-darwin-arm64" => "gix"
      end
    end

    if Hardware::CPU.intel?
      url "https://github.com/ademajagon/gix/releases/download/v0.3.1/gix-darwin-amd64"
      sha256 "1cdce745f24f57ff11570679e3bdef14e4bd7c53adf1ff089150c39b282a3984"

      def install
        bin.install "gix-darwin-amd64" => "gix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/ademajagon/gix/releases/download/v0.3.1/gix-linux-arm64"
      sha256 "aae2f84137f00021b16d1d572282db218b70ff4ccf36a146c0814acd917dbbde"

      def install
        bin.install "gix-linux-arm64" => "gix"
      end
    end

    if Hardware::CPU.intel?
      url "https://github.com/ademajagon/gix/releases/download/v0.3.1/gix-linux-amd64"
      sha256 "e28aed14510c4ed272474674c26389a0287a93e4827d8e1ba415a6d5da43110d"

      def install
        bin.install "gix-linux-amd64" => "gix"
      end
    end
  end

  test do
    system "#{bin}/gix", "--version"
  end
end
