# Formula/gix.rb
# Generated by util/formula_templater.sh — do not edit by hand.
# To update: ./util/formula_templater.sh gix <version>
class Gix < Formula
  desc "Git-enhancing CLI powered by AI"
  homepage "https://github.com/ademajagon/gix"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ademajagon/gix/releases/download/v0.3.0/gix-darwin-arm64"
      sha256 "f05e8e8c6b3d56dfa755c3412d4a1a835bf48906dd02345a64ddfad6a0d70974"

      def install
        bin.install "gix-darwin-arm64" => "gix"
      end
    end

    if Hardware::CPU.intel?
      url "https://github.com/ademajagon/gix/releases/download/v0.3.0/gix-darwin-amd64"
      sha256 "08574225980dc36e45460837df5257fe3c557310c1ac65f4fd59cad9ad5902a3"

      def install
        bin.install "gix-darwin-amd64" => "gix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/ademajagon/gix/releases/download/v0.3.0/gix-linux-arm64"
      sha256 "13774eda1dbcc033b55d4ca0f77ed6f8d7be4b80c4afa7866182ce78c6ce957a"

      def install
        bin.install "gix-linux-arm64" => "gix"
      end
    end

    if Hardware::CPU.intel?
      url "https://github.com/ademajagon/gix/releases/download/v0.3.0/gix-linux-amd64"
      sha256 "f3861af81e3d79f7dec3233bdbb259ded6a3ab180bf9f3866e7a91626d7fb7cb"

      def install
        bin.install "gix-linux-amd64" => "gix"
      end
    end
  end

  test do
    system "#{bin}/gix", "--version"
  end
end
